language: cpp

env: CXX_STANDARD=c++11

# Enable install caching to reduce install time in next builds
cache: ccache

compiler: g++

sudo: required

before_install:
  - cd ../
  - sudo mv gr-lora ../
  - cd ../
  
  # Add repos for more up-to-date versions of g++ and libboost
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  # Report correct versions are installed
  # - uname -a
  # - $CXX --version
  # - $CC --version
  
  - sudo pip install scipy
  - sudo apt-get install swig
  - sudo apt-get install libcppunit-dev
  - sudo apt-get install fftw3 fftw-dev

  - sudo apt-get install libboost1.55-all-dev
  - sudo ldconfig
  # This installs and old version, and is therefore deprecated
  # - sudo apt-get install gnuradio
  # - sudo ldconfig
  
  # Manual VOLK install
  # - git clone https://github.com/gnuradio/volk.git
  # - cd volk/
  # - git checkout v1.3
  # - mkdir build && cd build
  # - cmake ../
  # - make && sudo make install
  # - sudo ldconfig
  # - cd ../../
  
  # Manual GNURadio install
  - git clone https://github.com/gnuradio/gnuradio.git
  - cd gnuradio
  - git pull --recurse-submodules=on
  - git submodule foreach git pull origin master
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake -DENABLE_INTERNAL_VOLK=ON ../
  - make && sudo make install
  - sudo ldconfig
  - cd ../../
  
  # Manual liquidDSP install
  - git clone https://github.com/jgaeddert/liquid-dsp.git
  - cd liquid-dsp/
  - sudo sh ./bootstrap.sh
  - sh ./configure
  - make && sudo make install
  - sudo ldconfig
  - cd ../

before_script:
  - cd gr-lora
  - mkdir build && cd build
  - cmake ../

script:
  - make
  - sudo make install
  # - make test  # Will fail

notifications:
  email: false
